#!/bin/bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Chatwoot — User Data Script (Production)
# Executed on first boot by EC2 instances launched via the ASG
# ---------------------------------------------------------------------------

LOG_FILE="/var/log/chatwoot-userdata.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "[$(date)] Starting Chatwoot user-data script..."

# ---------------------------------------------------------------------------
# 1. System update & base packages
# ---------------------------------------------------------------------------
apt-get update -y
apt-get install -y \
  curl \
  git \
  unzip \
  jq \
  awscli \
  amazon-cloudwatch-agent \
  ruby \
  libssl-dev \
  libreadline-dev \
  zlib1g-dev

# ---------------------------------------------------------------------------
# 2. Retrieve secrets from AWS Secrets Manager
# ---------------------------------------------------------------------------
AWS_REGION="eu-west-3"
SECRET_ARN="chatwoot/production/app/env"

echo "[$(date)] Fetching application secrets from Secrets Manager..."
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --region "$AWS_REGION" \
  --secret-id "$SECRET_ARN" \
  --query SecretString \
  --output text)

export SECRET_KEY_BASE=$(echo "$SECRET_JSON" | jq -r '.SECRET_KEY_BASE')
export SMTP_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.SMTP_PASSWORD')
export MAILER_SENDER_EMAIL=$(echo "$SECRET_JSON" | jq -r '.MAILER_SENDER_EMAIL')

# RDS credentials
RDS_SECRET_ARN="chatwoot/production/rds/master-credentials"
RDS_JSON=$(aws secretsmanager get-secret-value \
  --region "$AWS_REGION" \
  --secret-id "$RDS_SECRET_ARN" \
  --query SecretString \
  --output text)

export DB_HOST=$(echo "$RDS_JSON" | jq -r '.host')
export DB_USERNAME=$(echo "$RDS_JSON" | jq -r '.username')
export DB_PASSWORD=$(echo "$RDS_JSON" | jq -r '.password')
export DB_NAME=$(echo "$RDS_JSON" | jq -r '.dbname')

# ---------------------------------------------------------------------------
# 3. Create chatwoot user
# ---------------------------------------------------------------------------
if ! id "chatwoot" &>/dev/null; then
  useradd -m -s /bin/bash chatwoot
fi

# ---------------------------------------------------------------------------
# 4. Install Ruby via rbenv (or use system package if pre-baked in AMI)
# ---------------------------------------------------------------------------
# NOTE: In production, prefer a pre-baked AMI with Ruby + Chatwoot already installed.
# This section is provided as a reference bootstrap.

CHATWOOT_VERSION="v3.11.0"
CHATWOOT_DIR="/home/chatwoot/chatwoot"

if [ ! -d "$CHATWOOT_DIR" ]; then
  echo "[$(date)] Cloning Chatwoot $CHATWOOT_VERSION..."
  sudo -u chatwoot git clone https://github.com/chatwoot/chatwoot.git "$CHATWOOT_DIR" --branch "$CHATWOOT_VERSION" --depth 1
fi

# ---------------------------------------------------------------------------
# 5. Write .env file for Chatwoot
# ---------------------------------------------------------------------------
cat > "$CHATWOOT_DIR/.env" <<EOF
# Auto-generated by user-data on $(date)
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# Database
DB_HOST=${DB_HOST}
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

# Redis — retrieve endpoint from SSM or hardcode if stable
# REDIS_URL=redis://...

# Storage
STORAGE_BUCKET_NAME=$(aws ssm get-parameter --name "/chatwoot/production/s3_bucket_name" --region "$AWS_REGION" --query "Parameter.Value" --output text 2>/dev/null || echo "chatwoot-production-storage")
AWS_REGION=${AWS_REGION}

# Mailer
MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
SMTP_PASSWORD=${SMTP_PASSWORD}

RAILS_ENV=production
NODE_ENV=production
RAILS_LOG_TO_STDOUT=true
EOF

chown chatwoot:chatwoot "$CHATWOOT_DIR/.env"
chmod 600 "$CHATWOOT_DIR/.env"

# ---------------------------------------------------------------------------
# 6. Start / restart Chatwoot services
# ---------------------------------------------------------------------------
echo "[$(date)] Restarting Chatwoot services..."
systemctl restart chatwoot.target 2>/dev/null || echo "systemd target not found — skipping"

# ---------------------------------------------------------------------------
# 7. CloudWatch Agent configuration
# ---------------------------------------------------------------------------
cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<'CWJSON'
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/chatwoot-userdata.log",
            "log_group_name": "/chatwoot/production/userdata",
            "log_stream_name": "{instance_id}"
          },
          {
            "file_path": "/home/chatwoot/chatwoot/log/production.log",
            "log_group_name": "/chatwoot/production/app",
            "log_stream_name": "{instance_id}"
          }
        ]
      }
    }
  }
}
CWJSON

systemctl enable amazon-cloudwatch-agent
systemctl restart amazon-cloudwatch-agent

echo "[$(date)] User-data script completed successfully."
