# Variables dans GitLab CICD:
#   AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY
#   AWS_DEFAULT_REGION

default:
  tags:
    - chatwoot-runner

stages:
  - validate
  - build-ami
  - plan-staging
  - plan-production
  - apply-staging
  - apply-production

# VALIDATE — toutes les MRs

format:
  stage: validate
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
  script:
    - terraform fmt -check -recursive infra/terraform/

validate-staging:
  stage: validate
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
  script:
    - terraform -chdir=infra/terraform/environments/staging init -backend=false
    - terraform -chdir=infra/terraform/environments/staging validate

validate-production:
  stage: validate
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
  script:
    - terraform -chdir=infra/terraform/environments/production init -backend=false
    - terraform -chdir=infra/terraform/environments/production validate

# BUILD AMI — rebuild en fonction de ce qu'il y a de changé

.packer-build:
  stage: build-ami
  image:
    name: hashicorp/packer:1.11
    entrypoint: [""]
  before_script:
    - apk add --no-cache ansible openssh-client
    - cd infra/packer
    - packer init .

build-ami:chatwoot:
  extends: .packer-build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - infra/packer/common.pkr.hcl
        - infra/packer/chatwoot.pkr.hcl
        - infra/ansible/chatwoot-playbook.yml
        - infra/docker/docker-compose-staging.yml
        - infra/docker/docker-compose-prod.yml
        - infra/docker/scripts/chatwoot-start.sh
        - infra/docker/config/nginx.conf
  script:
    - packer build -only=amazon-ebs.chatwoot .

build-ami:monitoring:
  extends: .packer-build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - infra/packer/common.pkr.hcl
        - infra/packer/monitoring.pkr.hcl
        - infra/ansible/monitoring-playbook.yml
        - infra/docker/docker-compose-monitoring.yml
        - infra/docker/scripts/monitoring-start.sh
        - infra/docker/config/prometheus-*.yml
        - infra/docker/grafana/**/*
  script:
    - packer build -only=amazon-ebs.monitoring .

build-ami:bastion:
  extends: .packer-build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - infra/packer/common.pkr.hcl
        - infra/packer/bastion.pkr.hcl
        - infra/ansible/bastion-playbook.yml
  script:
    - packer build -only=amazon-ebs.bastion .

# PLAN STAGING — toutes les Merge Requests

plan-staging:
  stage: plan-staging
  needs:
    - job: build-ami:chatwoot
      optional: true
    - job: build-ami:monitoring
      optional: true
    - job: build-ami:bastion
      optional: true
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  script:
    - terraform -chdir=infra/terraform/environments/staging init
    - terraform -chdir=infra/terraform/environments/staging plan -no-color -out=staging.tfplan
  artifacts:
    paths:
      - infra/terraform/environments/staging/staging.tfplan
    expire_in: 1 day

# PLAN PRODUCTION — merge vers main

plan-production:
  stage: plan-production
  needs:
    - job: build-ami:chatwoot
      optional: true
    - job: build-ami:monitoring
      optional: true
    - job: build-ami:bastion
      optional: true
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  script:
    - terraform -chdir=infra/terraform/environments/production init
    - terraform -chdir=infra/terraform/environments/production plan -no-color -out=production.tfplan
  artifacts:
    paths:
      - infra/terraform/environments/production/production.tfplan
    expire_in: 1 day

# APPLY STAGING — merge vers main en automatique

apply-staging:
  stage: apply-staging
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  needs:
    - plan-staging
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  script:
    - terraform -chdir=infra/terraform/environments/staging init
    - terraform -chdir=infra/terraform/environments/staging apply -auto-approve

# APPLY PRODUCTION — intervention manuel en plus pour plus de sécurité

apply-production:
  stage: apply-production
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  needs:
    - plan-production
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  script:
    - terraform -chdir=infra/terraform/environments/production init
    - terraform -chdir=infra/terraform/environments/production apply -auto-approve
