server {
  listen 80;
  server_name _;
  # Chatwoot relies on underscore in headers for API
  underscores_in_headers on;

  # Force dynamic DNS resolution via Docker's internal resolver
  resolver 127.0.0.11 valid=10s;

  location / {
    set $upstream rails:3000;
    proxy_pass_header Authorization;
    proxy_pass http://$upstream;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_buffering off;
    client_max_body_size 0;
    proxy_read_timeout 36000s;
    proxy_redirect off;
  }
}