- hosts: all
  become: true
  tasks:
  - name: Update apt
    apt:
      update_cache: true
      upgrade: dist

  - name: Installer fail2ban et ufw
    apt:
      name:
        - fail2ban
        - ufw
      state: present

#-----------------SSH Hardening

  - name: Changer le port SSH à 2022
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?Port '
      line: 'Port 2022'

  - name: Désactiver le login root SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin no'

  - name: Désactiver authentification password
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PasswordAuthentication'
      line: 'PasswordAuthentication no'

#-----------------Fail2ban

  - name: Configurer fail2ban pour SSH
    copy:
      dest: /etc/fail2ban/jail.local
      content: |
        [sshd]
        enabled = true
        port = 2022
        maxretry = 3
        bantime = 3600
        findtime = 600

  - name: Activer et démarrer fail2ban
    systemd_service:
      name: fail2ban
      enabled: yes
      state: started

#-----------------UFW

  - name: Bloquer tout le trafic entrant par défaut
    ufw:
      default: deny
      direction: incoming

  - name: Autoriser tout le trafic sortant par défaut
    ufw:
      default: allow
      direction: outgoing

  - name: Autoriser SSH sur le port 2022
    ufw:
      rule: allow
      port: '2022'
      proto: tcp

  - name: Activer UFW
    ufw:
      state: enabled

#-----------------Restart services

  - name: Redémarrer sshd
    systemd_service:
      name: ssh
      state: restarted
