- hosts: all
  become: true
  tasks:
  - name: Update apt
    apt:
      update_cache: true
      upgrade: dist

  - name: Installer les packages utiles
    apt:
      name:
        - curl
        - unzip
        - awscli

  - name: Installer Docker
    shell: curl -fsSL https://get.docker.com | sh

  - name: Créer le dossier de l'app
    file:
      path: /app/monitoring
      state: directory

  - name: Copier le docker-compose monitoring
    copy:
      src: ../docker/docker-compose-monitoring.yml
      dest: /app/monitoring/docker-compose-monitoring.yml

  - name: Copier la config Prometheus
    copy:
      src: ../docker/config/prometheus.yml
      dest: /app/monitoring/prometheus.yml

  - name: Copier le script de boot
    copy:
      src: ../docker/scripts/monitoring-start.sh
      dest: /app/monitoring/monitoring-start.sh
      mode: "0755"

  - name: Créer le service systemd
    copy:
      dest: /etc/systemd/system/monitoring.service
      content: |
        [Unit]
        Description=Monitoring Stack
        After=docker.service
        Requires=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/app/monitoring/monitoring-start.sh

        [Install]
        WantedBy=multi-user.target

  - name: Activer le service au boot
    systemd_service:
      name: monitoring
      enabled: yes
      daemon_reload: true
